# Generated by Django 4.0.4 on 2022-05-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('start_date_time', models.IntegerField()),
                ('end_date_time', models.IntegerField()),
            ],
        ),
    ]
