# Generated by Django 4.0.4 on 2022-05-07 05:41

from django.db import migrations
import uuid


def add_uuid(apps, schema_editor):
	new_uuid = uuid.uuid4()
	
	Employee = apps.get_model('landingpage', 'Employee')
	for emp in Employee.objects.all():
		emp.id = new_uuid
		emp.save()


class Migration(migrations.Migration):

	dependencies = [
		('landingpage', '0003_alter_employee_name'),
	]

	operations = [
		migrations.RunPython(add_uuid)
	]
